#!/usr/bin/env ruby

require_relative "lib/spaces"
require_relative "lib/grid"
require_relative "lib/delegate"

# fix this uglyness
maps = [
[" ----- 
|@ %  |
|   & |
|     >
 ----- 
", [7, 7]],
[" ------- 
|       |
|       |
|       |
|       |
 -------
",9, 5]]

delegate = Delegate.new

until maps.empty?

	map = maps.shift
	grid = Grid.from_map(*map[1], map[0])
	delegate.grid = grid

	until delegate.grid.complete?
		puts delegate.grid
		delegate.parse(gets.chomp.downcase)
		puts
	end

end