#!/usr/bin/env ruby

require_relative "lib/spaces"
require_relative "lib/grid"
require_relative "lib/delegate"

# grid = Grid.new(3, 3)
map = <<EOT
 ----- 
|@ ^  |
|     |
|     |
 ----- 
EOT

grid = Grid.from_map(7, 7, map)

delegate = Delegate.new(grid)

loop do
	puts delegate.grid
	delegate.parse(gets.chomp.downcase)
	puts
end
